export default {
    "recipes": [
        {
            "id": 1,
            "recipe_name": "Lemon Bars",
            "url": "https://www.erinliveswhole.com/healthy-lemon-bars-gluten-free/?utm_medium=social&utm_source=pinterest&utm_campaign=tailwind_tribes&utm_content=tribes&utm_term=792671610_32946700_178868",
            "description": "A delicious snack or dessert. Summertime",
            "notes": "Paleo",
            "img_url": "https://www.erinliveswhole.com/wp-content/uploads/2019/07/lemon-bars-5.jpg",
            "date_created": "2019-01-03T00:00:00.000Z",
            "user_id": 5,
        },
        {
            "id": 2,
            "recipe_name": "Spinach Cilantro Meatballs",
            "url": "https://www.savorylotus.com/spinach-cilantro-meatballs-grain-free/?utm_content=buffer4985f&utm_medium=social&utm_source=pinterest.com&utm_campaign=WNMbuffer",
            "description": "Yummy meatballs that are quick to put together.",
            "notes": "Maybe cook less than specified time.",
            "img_url": "https://www.savorylotus.com/wp-content/uploads/2014/03/Spinach-Cilantro-Meatballs.jpeg",
            "date_created": "2018-08-15T23:00:00.000Z",
            "user_id": 4,
        },
        {
            "id": 3,
            "recipe_name": "Chicken Soup",
            "url": "https://againstallgrain.com/2018/01/05/whole30-instant-pot-chicken-soup-recipe/",
            "description": "Warm, delicious soup.",
            "notes": "Instant Pot",
            "img_url": "https://againstallgrain.com/wp-content/uploads/2018/01/IMG_5015.jpg",
            "date_created": "2018-03-01T00:00:00.000Z",
            "user_id": 3,
        },
        {
            "id": 4,
            "recipe_name": "Chocolate Chip Cookies",
            "url": "https://againstallgrain.com/2012/08/29/real-deal-chocolate-chip-cookies/",
            "description": "Excellent, healthier chocolate chip cookies.",
            "notes": "Paleo",
            "img_url": "https://againstallgrain.com/wp-content/uploads/2012/08/ChocolateChipCookies.jpg",
            "date_created": "2019-01-04T00:00:00.000Z",
            "user_id": 2,
        },
        {
            "id": 5,
            "recipe_name": "Pork Tenderloin",
            "url": "https://thebetteredblondie.com/the-best-instant-pot-pork-tenderloin/",
            "description": "Simple and easy way to cook pork tenderloin.",
            "notes": "Instant Pot",
            "img_url": "https://i2.wp.com/thebetteredblondie.com/wp-content/uploads/2019/06/IMG_0475.jpg?w=1927&ssl=1",
            "date_created": "",
            "user_id": 1,
        },
    ]
}